version: '3.8'
services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
      - API_BASE_URL=https://api.example.com
    # Geliştirici için hot-reload (opsiyonel):
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
